# Generated by Django 4.2.7 on 2023-12-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="progress",
            field=models.CharField(default="In progress", max_length=100),
        ),
    ]
